"$schema" = "node_modules/wrangler/config-schema.json"
# wrangler.toml
name = "fr-frontend"
main = ".output/server/index.mjs"
compatibility_date = "2025-08-04"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".output/public"

[observability]
enabled = true